name: publish-build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew chiseledBuild

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            versions/*/build/libs/*.jar
            !versions/*/build/libs/*-sources.jar

      - name: upload jars to release
        run: |
          find versions -path '*/build/libs/*.jar' ! -name '*-sources.jar' -print0 |
          xargs -0 gh release upload "${{ github.event.release.tag_name }}"
        env:
          GH_TOKEN: ${{ github.token }}
